apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::907069229663:role/eksctl-deploy-demo-nodegroup-ng-9-NodeInstanceRole-11V7L54LRM0H7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::907069229663:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-07T03:39:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1714"
  uid: 66e92cb9-3b74-4a39-bd59-ec571416d07b
